name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.102

      - name: Restore
        run: dotnet restore PhoneBook.sln

      - name: Build
        run: dotnet build PhoneBook.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test PhoneBook.sln --configuration Release --no-build
